#!/usr/bin/env python3

"""
@file zappy_ai
"""

import argparse

from src.Player import Player
from src.Utils.OSUtils import get_pid


def process_args():
    """
    @brief Parse command line arguments and return them.

    @return args Command line arguments
    """
    parser = argparse.ArgumentParser(description="USAGE: \
                        ./zappy_ai -p port -n name -h machine", add_help=False)
    parser.add_argument("-p", type=int, required=True,
                        help="Port number", metavar="PORT")
    parser.add_argument("-n", type=str, required=True,
                        help="Name of the team", metavar="NAME")
    parser.add_argument("-h", type=str, default="localhost", help="Name of the machine; \
                        localhost by default", metavar="MACHINE")
    parser.add_argument("-H", "--help", action="help", default=argparse.SUPPRESS, help="Show \
                        this help message and exit")
    args = parser.parse_args()
    return args


def main():
    """
    @brief Parse command line arguments and print the IP address and port.

    @param port Port of the server
    @param name Name of the team
    @param machine Name of the machine; localhost by default
    """
    args = process_args()

    p = Player(args.p, args.h, args.n, broadcast_key=get_pid())
    try:
        while p.think():
            pass
        return 0
    except KeyboardInterrupt:
        return 0
    except RuntimeError as e:
        if p.my_drone.level >= 7: # server disconnected automatically
            print("Congratulations, I won! (aHR0cHM6Ly95b3V0dS5iZS9oRHQ0VHEyWlBLSQ==)")
            return 0
        print("Main:", e)
        return 84


if __name__ == "__main__":
    main()
